security:
    encoders:
        App\Entity\User:
            algorithm: auto
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_database:
            entity:
                class: App\Entity\User
                property: username
        #        database_users:
        #            entity: { class: App\Entity\User, property: username}
        in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/sgadblog
            anonymous: true

            provider: in_database

            form_login:
                login_path: admin_connexion
                check_path: admin_connexion
                default_target_path: dashboard
                always_use_default_target_path: true
                csrf_token_generator: security.csrf.token_manager

            logout:
                path: admin_deconnexion
                target: admin_connexion
        main:
            provider: in_database
            anonymous: true
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

        #    role_hierarchy:
        #        ROLE_ADMIN: ROLE_USER
        # Easy way to control access for large sections of your site
        # Note: Only the *first* access control that matches will be used
    access_control:
        # access login back
        - { path: ^/sgadblog/account/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sgadblog/account/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # role admin requis pour le back
        - { path: ^/sgadblog, roles: ROLE_ADMIN }
