<?php


namespace App\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContactType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'required' => true,
                'label' =>'Votre nom',
                'attr' => ['placeholder' => 'Entrez votre nom']
            ])
            ->add('mail', EmailType::class, [
                'required' => true,
                'label' =>'Votre email',
                'attr' => ['placeholder' => 'Entrez votre email']
            ])
            ->add('phone', NumberType::class, [
                'required' => false,
                'label' =>'Votre numéro de téléphone',
                'attr' => ['placeholder' => 'Entrez votre numéro de téléphone']
            ])
            ->add('message', TextareaType::class, [
                'required' => true,
                'label' =>'Votre message',
                'attr' => ['placeholder' => 'Entrez votre message']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }
}
